Models/BaseEntity.cs
namespace GamerCorner.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
        [MaxLength(250)]
        public string Name { get; set; } = string.Empty;
    }
}

Models/Category.cs
namespace GamerCorner.Models
{
    public class Category : BaseEntity
    {
     public ICollection<Game> Games { get; set; } = new List<Game>();
    }
}

Models/Device.cs
namespace GamerCorner.Models
{
    public class Device : BaseEntity
    {
        [MaxLength(200)]
        public string Icon { get; set; } =string.Empty;
    }
}

Models/ErrorViewModel.cs
namespace GamerCorner.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Game.cs
namespace GamerCorner.Models
{
    public class Game : BaseEntity
    {
     
        [MaxLength(2550)]
        public string Description { get; set; } = string.Empty;

        [MaxLength(500)]
        public string Cover { get; set; } = string.Empty;

        public int CategoryId { get; set; }
        public Category category { get; set; } = default!;

        public ICollection<GameDevice> Device { get; set; } = new List<GameDevice>();

    }
}

Models/GameDevice.cs
namespace GamerCorner.Models
{
    public class GameDevice
    {
        public int GameId { get; set; }
        public Game Game { get; set; } = default!;

        public int DeviceId { get; set; }
        public Device Device { get; set; } = default!;

    }
}

Controllers/HomeController.cs
namespace GamerCorner.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGameService _gameService;

        public HomeController(IGameService gameService)
        {
            _gameService = gameService;
        }

        public IActionResult Index()
        {
            var games = _gameService.GetAllGames();
            return View(games);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/gamesController.cs
namespace GamerCorner.Controllers
{
    public class gamesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICategoryService _categoryService;
        private readonly IDeviceService _deviceService;
        private readonly IGameService _gameService;

        public gamesController(ApplicationDbContext context, ICategoryService categoryService, IDeviceService deviceService, IGameService gameService)
        {
            _categoryService = categoryService;
            _context = context;
            _deviceService = deviceService;
            _gameService = gameService;
        }


        public IActionResult Index()
        {
            var games = _gameService.GetAllGames();
            return View(games);
        }

        public IActionResult Details(int id)
        {
            var game = _gameService.GetGameById(id);
            if(game == null)
                return NotFound($"Not Found Game With ID: {id}");

            return View(game);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var categories = _context.Categories.ToList();
            CreateGameFormViewModel viewModel = new()
            {
                Categories = _categoryService.GetSelectList(), 

                Devices = _deviceService.GetSelectDeviceLists()
            };
            return View(viewModel);
        }

        [HttpPost]
        //For Secure Our Website
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = _categoryService.GetSelectList();

                model.Devices = _deviceService.GetSelectDeviceLists();

                return View(model);
            }
            await _gameService.Create(model);
           
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Home/Index.cshtml
@model IEnumerable<Game>

@{
    ViewData["Title"] = "Home Page";
}

<div class="row mt-5">
    @foreach (var game in Model)
    {
        <div class="col-lg-4 col-md-6">
            <div>
                <a class="card border-success mb-3 text-decoration-none rounded rounded-3 overflow-hidden" asp-controller="games" asp-action="Details" asp-route-id="@game.Id">
                    <div class="card-body" style="background-image: url(@($"{FileSetting.imagePath}/{game.Cover}"))
                            ;background-size:cover; background-position:center;height: 500px;">
                        <div class="h-100 d-flex align-items-end">
                            <span class="badge bg-secondary rounded-0">@game.category?.Name</span>
                        </div>
                        </div>
                    <div class="card-footer text-muted d-flex justify-content-between align-items-center">
                        <h5 style="width:130px">@game.Name</h5>
                        <div>
                            @foreach (var gameDevice in game.Device)
                            {
                                <i class="@gameDevice.Device.Icon me-1 fs-3"></i>
                            }
                        </div>
                    </div>
                </a>
            </div>
        </div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> GamerCorner | @ViewData["Title"]</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/GamerCorner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light mb-3" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GamerCorner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="games" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1447 - GamerCorner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/games/Create.cshtml
@model CreateGameFormViewModel
@{
    ViewData["Title"] = "Add Game";
}

<p>Create Game</p>
<h4><i class="bi bi-plus-circle-dotted btn-lg"></i>
    Add new Game</h4>

<form asp-controller="games" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Enter Game Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="form-label mt-4"></label>
                <select class="form-select" asp-for="CategoryId" asp-items="Model.Categories"
                data-placeholder="Select Category" data-minimum-results-for-search="Infinity">
                    <option value=""></option>                  
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select" asp-for="SelectedDevices" asp-items="Model.Devices"
                        data-placeholder="Select Platform"> 
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Game Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control"  asp-for="Cover"
                       data-rule-extension="@FileSetting.allowedExtension.Replace(".", string.Empty)" data-msg-extension="Not Allowed"
                       data-rule-fileSize="@FileSetting.maxFileSizeInBytes"
                       data-msg-fileSize="Max File Size Is @FileSetting.maxFileSizeInMB MB">
                @* Here we Replace '.' With Empty Strig because Libarary Can not read '.'*@

                <small class="form-text text-muted">Only Support @FileSetting.allowedExtension @(FileSetting.maxFileSizeInMB)MB </small>
            </div>
                <span asp-validation-for="Cover" class="text-danger d-block"></span>
            <button type="submit" class="btn btn-light text-bg-primary mt-3">Save</button>   
            </div>
        
        <div class="col-md-6 d-flex justify-content-center overflow-hidden">
            <img class="cover-preview d-none" alt="Cover">
        </div>
        </div>
</form>

@* Client Side Validation with jQuery File *@
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/filesize.js" asp-append-version="true"></script>
    <script src="~/js/game.js" asp-append-version="true"></script>
}

Views/games/Details.cshtml
@model Game

@{
    ViewData["Title"] = Model.Name;
}

<div class="card border-success rounded rounded-3 mt-3 overflow-hidden"> 
    <div class="card-body p-0">
        <div class="row">
            <div class="col-md-8 px-5 py-4 d-flex flex-column justify-content-between">
                <div>
                    <h1 class="text-success fw-bolder">@Model.Name</h1>
                    <span class="badge bg-info fs-4 mb-4">@Model.category?.Name</span>
                    <p class="fs-4">@Model.Description</p>
                </div>
                <div>
                    @foreach (var gameDevice in Model.Device)
                    {
                        <i class="@gameDevice.Device.Icon me-1 fs-3 text-secondary"></i>
                    }
                </div>
            </div>
            <div class="col-md-4">
                <img src="@($"{FileSetting.imagePath}/{Model.Cover}")" alt="Model.Name" class="w-100"/>
            </div>
        </div>
    </div>
</div>

Views/games/Index.cshtml
@model IEnumerable<Game>

@{
    ViewData["Title"] = "Games";
}

<a class="btn btn-secondary" asp-action="Create">
    <i class="bi bi-plus-circle-dotted btn-lg"></i>
    Add Game
</a>

<div class="mt-5">
    <table class="table table-bordered border-primary">
        <tbody>
            @foreach(var game in Model)
            {
                <tr class="border-1 border-success">
                    <td>
                        <div class="d-flex">
                            <div class="pe-3"><img src="@($"{FileSetting.imagePath}/{game.Cover}")" alt="@game.Name" 
                                style="max-width:100px" /></div>
                        </div>
                        <div class="d-flex flex-column justify-content-center">
                            <h4 class="text-light">@game.Name</h4>
                            <h5>@game.category.Name</h5>
                        </div>
                    </td>
                    <td class="d-flex justify-content-end">
                        <div>
                            <a class="btn btn-info rounded rounded-2 me-2" asp-action="Update" asp-route-id="@game.Id">
                                <i class="bi bi-pencil-fill"></i>
                            </a>
                            <a herf="#" class="btn btn-danger rounded rounded-2">
                                <i class="bi bi-trash3"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>